name: dedebt_application
description: "A new Flutter project."
publish_to: 'none'

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  motion_tab_bar_v2: ^0.3.0
  go_router: ^13.0.1
  firebase_core: ^2.25.3
  firebase_auth: ^4.17.3
  sign_in_button: ^3.2.0
  google_sign_in: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/images/Logo.png

  uses-material-design: true

 