name: dedebt_application
description: "A new Flutter project."
publish_to: "none"

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  motion_tab_bar_v2: ^0.3.0
  go_router: ^13.0.1
  google_fonts: ^6.1.0
  firebase_core: ^2.25.1
  firebase_auth: ^4.17.4
  sign_in_button: ^3.2.0
  google_sign_in: ^6.0.2
  firebase_core_dart: ^1.0.1
  cloud_firestore: ^4.15.4
  toggle_switch: ^2.1.0
  dropdown_textfield: 1.0.8
  easy_date_timeline: ^1.0.5
  pdf: ^3.10.8
  printing: ^5.12.0
  path_provider: ^2.1.2
  flutter_cache_manager: ^3.3.1
  flutter_cached_pdfview: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/images/Logo.png
    - assets/images/googleLogo.png

    - assets/images/
  uses-material-design: true
